routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/editor', 'CKEditorController');

Route::get('/', "DomaineController@accueil")->name('accueil');
Route::post('/search', "StageController@search")->name('search');
Route::resource('domaine', 'DomaineController');
Route::resource('stage', "StageController");
Route::resource('promotion',"PromotionController");
Route::get('/mail',"ContactController@sendEmailtoUser");
Route::get('/contact/{id}',"PromotionController@contactPP")->name('contactPromotion');
Route::post('/contactPP',"ContactController@contactPP")->name('contactPP');
Route::post('/renseignement',"ContactController@demandeRenseignement")->name('renseignement');
Route::get('/fiche/{id}',"FicheController@show")->name('showFiche');
Route::post('/fiche',"FicheController@insert")->name('insertFiche');


// Blocage
Route::get('/fiche', function () { return redirect('/'); });
Route::get('/search', function () { return redirect('/'); });

// Route d'authentification
Auth::routes(['register' => false], ['reset' => false]);
// Route d'administration
Route::GET('/admin', 'AdminController@index')->name('admin');
// CRUD Stage Admin
Route::GET('/admin/stages', 'AdminController@getAllStages')->name('stages');
Route::POST('/admin/stages', 'AdminController@searchStages')->name('searchStages');
Route::POST('/admin/stages/insert', 'AdminController@insertStages')->name('insertStages');
Route::DELETE('/admin/stages/delete', 'AdminController@deleteStages')->name('deleteStages');
Route::PUT('/admin/stages/update', 'AdminController@updateStages')->name('updateStages');
// CRUD Domaine ADMIN
Route::GET('/admin/domaines', 'AdminController@getAllDomaines')->name('domaines');
Route::POST('/admin/domaines', 'AdminController@searchDomaines')->name('searchDomaines');
Route::POST('/admin/domaines/insert', 'AdminController@insertDomaines')->name('insertDomaines');
Route::DELETE('/admin/domaines/delete', 'AdminController@deleteDomaines')->name('deleteDomaines');
Route::PUT('/admin/domaines/update', 'AdminController@updateDomaines')->name('updateDomaines');
// CRUD Promotion ADMIN
Route::GET('/admin/promotions', 'AdminController@getAllPromotions')->name('promotions');
Route::POST('/admin/promotions', 'AdminController@searchPromotions')->name('searchPromotions');
Route::POST('/admin/promotions/insert', 'AdminController@insertPromotions')->name('insertPromotions');
Route::DELETE('/admin/promotions/delete', 'AdminController@deletePromotions')->name('deletePromotions');
Route::PUT('/admin/promotions/update', 'AdminController@updatePromotions')->name('updatePromotions');
// CRUD Administrateurs ADMIN
Route::GET('/admin/administrateurs', 'AdminController@getAllAdministrateurs')->name('administrateurs')->middleware('superAdmin');
Route::POST('/admin/administrateurs/insert', 'AdminController@insertAdministrateurs')->name('insertAdministrateurs')->middleware('superAdmin');
Route::DELETE('/admin/administrateurs/delete', 'AdminController@deleteAdministrateurs')->name('deleteAdministrateurs')->middleware('superAdmin');
Route::PUT('/admin/administrateurs/update', 'AdminController@updateAdministrateurs')->name('updateAdministrateurs')->middleware('superAdmin');
// CRUD Fiche ADMIN
Route::GET('/admin/fiches', 'AdminController@getAllFiches')->name('fiches');
Route::POST('/admin/fiches', 'AdminController@searchFiches')->name('searchFiches');
Route::PUT('/admin/fiches/update', 'AdminController@updateFiches')->name('updateFiches');

resources/views/accueil.blade.php
@extends('template')

@section('title', 'Accueil')

@section('content')
<style>
input::-webkit-calendar-picker-indicator {
  position: absolute;
  width: 100%;
  height: 100%;
  opacity: 0;
}

@media (max-width: 768px) {
    .w-75 {
        width: 30%!important;
      }
    .captcha {
      padding: 1rem;
    }
}
</style>

  <div id="titre" class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center text-white bg-light" style="background-color: #49894B!important;box-shadow: 4px 4px 6px gray;">
      <div class="row">
            <div class="col-md-6 p-lg-5">
                <img style="width: 80%;" src="{{ asset('storage/logo-sans-fond.png') }}"></img>
                <h2 class="text-center">Le choix à portée de main</h2>
            </div>
            <div class="col-md-6">
                <img class="img_logo" style="width: 40%;" src="{{ asset('storage/logo.png') }}"></img>
            </div>
      </div>
  </div>

  <div id="domaine" class="position-relative overflow-hidden p-3 p-md-5 m-md-3 bg-light" style="background-color: #084F7A!important;box-shadow: 4px 4px 6px gray;">
    <h2 class="text-center p-3 text-white">Nos différents domaines de formations</h2>
    <div class="container-fluid">
    </div>
    <div class="card-deck">
        @foreach($domaines as $domaine)
      <div class="card card-custom bg-white border-white">
          <div class="card-custom-img" style="background-image: url({{ asset('/') }}storage/{{ $domaine->image }});"></div>
          <div class="card-custom-avatar">
            <img class="img-fluid" src="{{ asset('/') }}storage/{{ $domaine->logo }}" alt="Icone" />
          </div>
          <div class="card-body" style="overflow-y: auto">
          <h4 class="card-title" style="text-align: center">{{$domaine->nom}}</h4>
            <p class="card-text text-center">{{$domaine->description}}</p>
          </div>
          <div class="card-footer text-center" style="background: inherit; border-color: inherit;">
            <a class="btn btn-outline-dark" href="{{ route('domaine.show', ['domaine' => $domaine->id]) }}" role="button">Ici toutes les actus stages</a>
          </div>
        </div>
        @endforeach
    </div>
    <form action="{{ route('search') }}" method="POST">
    @csrf
      <div class="row">
      <div class="col-md-12 pt-3">
        <h3 class="text-center p-3 text-white">Faites nous part de votre recherche par date ou par mots clés</h3>
      </div>
      <div class="col-md-6">
        <div class="input-group mb-3">
          <input class="form-control form-control-lg" type="date" name="rechercheDate" max="3000-12-31"min="1000-01-01" class="form-control">
          <div class="input-group-append">
            <span class="input-group-text" id="datepickericon"><i class="far fa-calendar-alt"></i></span>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group mb-3">
            <input type="text" class="form-control form-control-lg" name="recherche" placeholder="Mots clés : Commerce, Info, BTS SIO">
            <div class="input-group-append">
              <button class="btn btn-success" type="submit"><i class="fas fa-search"></i></button>
            </div>
        </div>
      </div>
    </div>
    </form>
    <h2 class="text-center p-3 text-white">Les stages à venir</h2>
    <div class="card-deck">
    @foreach($stages as $s)
    <div class="card">
        <div class="card-body">
        <h6 class="card-title text-center">{{ $s->promotion->domaine->nom }}</h6>
          <p class="card-text text-center"><span class="badge badge-success">{{ Carbon\Carbon::parse($s->dateDebut)->format('d-m-Y') }}</span> au <span class="badge badge-success">{{ Carbon\Carbon::parse($s->dateFin)->format('d-m-Y') }}</p>
          <p class="card-text text-center">{{ $s->promotion->nom }}</p>
          <p class="card-text text-center">{{ $s->promotion->description }}</p>
          <div class="text-center">
          <form method="POST" action="{{ route('search') }}">
            @csrf
            <input name="statut" type="hidden" value="show">
            <input name="recherche" type="hidden" value="{{ $s->promotion->nom }}">
            <button type="submit" class="btn btn-success"><i class="far fa-eye"></i> Ouvrir les détails</button>
          </form>
          </div>
        </div>
      </div>
    @endforeach
    </div>
  </div>
</div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    <div id="carte" class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="
    background-color:#921853!important;box-shadow: 4px 4px 6px gray;">
      <div class="my-3 py-3">
        <img src="{{url ('../public/storage/logo-lycee.png')}}" style="width: 100%;"></img>
      </div>
    </div>
    <div id="carte"class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="
    background-color:#C79129!important;box-shadow: 4px 4px 6px gray;">
      <div class="my-3 p-3">
        <h2 class="display-5">Le lycée</h2>
        <p class="lead">Situé au centre-ville de Dole dans le Jura, le Lycée Pasteur Mont Roland offre un panel de formations
                         diverses et variées allant de la 3e jusqu'à la Licence en passant par le Bac et le BTS. Il accueille
                         1100 élèves dont 400 en formation post-bac de Bac+2 à Bac+4. Les formations qu'il propose sont regroupées
                         en 4 grands domaines qui sont le numérique, la santé & le social, l'art & le design et le commerce & le management</p>
      </div>
    </div>
  </div>
    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3" id="contact">
        <div id="titre" class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="background-color: #82B137!important;box-shadow: 4px 4px 6px gray;">
            <div class="my-3 py-3">
            <h2 class="display-5">Où nous-trouver</h2>
            <div class="map-responsive">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2716.238034387861!2d5.491666015489311!3d47.09440407915407!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478d4c97319a022b%3A0x10455424f077465e!2sLycee%20Pasteur%20Mont%20Roland%20P%C3%B4le%20Alternance%20Formation!5e0!3m2!1sfr!2sfr!4v1583831803907!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
            </div>
        </div>
        <div id="carte"class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="box-shadow: 4px 4px 6px gray;">
          <div class="my-3 p-3">
              <h2 class="display-5">Nous contacter</h2>
          </br>
          <p class="lead text-center">Une remarque, une suggestion, un renseignement ? Remplissez ce formulaire pour toutes demandes annexes au site</p>
          @if ($errors->any())
          <div class="col-md-12 text-center p-3">
            <div class="alert alert-danger" role="alert">
              @foreach ($errors->all() as $error)
                  <p style="margin-bottom: 0rem;"><i class="fas fa-times"></i> {{ $error }}</p>
              @endforeach
            </div>
          </div>
          @endif
          @if (session('status'))
          <div class="col-md-12 text-center p-3">
            <div class="alert alert-success" role="alert">
                <i class="fas fa-check"></i> {{ session('status') }}
            </div>
          </div>
          @endif
              <form action="{{ route('renseignement') }}" method="POST">
                  @csrf
                  <div class="form-row p-2">
                      <div class="col-md-3">
                          <label>Identité</label>
                      </div>
                      <div class="col-md-9">
                          <input type="text" placeholder="Exemple : Marie Dupont" class="form-control" name="identite" value="{{ old('identite') }}" required>
                      </div>
                  </div>
                  <div class="form-row p-2">
                      <div class="col-md-3">
                          <label>Adresse mail</label>
                      </div>
                      <div class="col-md-9">
                          <input type="email" placeholder="Exemple : contact@1mix.com" class="form-control" name="email" value="{{ old('email') }}" required>
                      </div>
                  </div>
                  <div class="form-row p-2">
                      <div class="col-md-3">
                          <label>Votre message</label>
                      </div>
                      <div class="col-md-9">
                          <textarea class="form-control" maxlength="1500" name="message" rows="5" required>{{ old('message') }}</textarea>
                      </div>
                  </div>
                  <div class="form-row p-2">
                      <div class="col-md-3">
                          <label>Captcha</label>
                      </div>
                      <div class="col-md-6">
                        <input type="text" class="form-control" name="captcha" minlength="6" maxlength="6" required>
                      </div>
                      <div class="col-md-3 captcha">
                          <img class="w-75 img-thumbnail" src="{!! Captcha::src() !!}"></img>
                      </div>
                  </div>
              <button class="btn btn-success" type="submit"><i class="fas fa-paper-plane"></i> Envoyer</a>
              </form>
          </div>
        </div>
    </div>
  <footer class="container py-5">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">Trouve ton stagiaire &copy; 2020 - Réalisé avec <i class="fas fa-heart"></i> par Mathis Djekhar, Thomas Guinchard, Remy Fejoz, Calvin Massot</small>
      </div>
    </div>
  </footer>
@stop

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Administration</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Bienvenue <b>{{ Auth::user()->name }}</b>, vous êtes connecté !
                </div>
            </div>
        </div>

        <div class="col-md-12" style="padding: 10px;">
          <div class="card-deck">
            <div class="card">
              <img class="card-img-top" src="{{url('/storage/stagiaire.jpg')}}" alt="Gestion des stages">
              <div class="card-body text-center">
                <h5 class="card-title">Gestion des stages</h5>
                <a class="btn btn-success w-100" href="{{ route('stages') }}" role="button"><i class="fas fa-cogs"></i> Gérer les stages</a>
              </div>
            </div>
            <div class="card">
              <img class="card-img-top" src="{{url('/storage/domaines.jpg')}}" alt="Gestion des domaines">
              <div class="card-body text-center">
                <h5 class="card-title">Gestion des domaines</h5>
                <a class="btn btn-success w-100" href="{{ route('domaines') }}" role="button"><i class="fas fa-cogs"></i> Gérer les domaines</a>
              </div>
            </div>
            <div class="card">
              <img class="card-img-top" src="{{url('/storage/promotions.jpg')}}" alt="Gestion des promotions">
              <div class="card-body text-center">
                <h5 class="card-title">Gestion des promotions</h5>
                <a class="btn btn-success w-100" href="{{ route('promotions') }}" role="button"><i class="fas fa-cogs"></i> Gérer les promotions</a>
              </div>
            </div>
          </div>
        </div>
    </div>

@endsection

resources/views/contactpp.blade.php
@extends('template')

@section('title', 'Contacter le professeur principal')

@section('content')
<link rel="stylesheet" href="{{ asset('/css/landing-page.css') }}">

<style>
header.masthead {
    position: relative;
    background-color: #343a40;
    background: url({{ asset('storage/fiche.jpg') }}) no-repeat center center;
    background-size: cover;
    padding-top: 8rem;
    padding-bottom: 8rem;
}

input::-webkit-calendar-picker-indicator {
  position: absolute;
  width: 100%;
  height: 100%;
  opacity: 0;
}

@media (max-width: 768px) {
    .w-75 {
        width: 30%!important;
      }
    .captcha {
      padding-bottom: 1rem;
    }
}
</style>


<header class="masthead text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <h1 class="mb-5">Contacter le professeur principal</h1>
      </div>
    </div>
  </div>
</header>

<section class="testimonials text-center bg-light pt-5">
    <div class="container">

      <div class="d-flex justify-content-center" id="buttonBack">
        <a class="btn btn-danger" href="{{ URL::previous() }}" role="button"><i class="fas fa-arrow-circle-left"></i> Retour</a>
      </div>

      <div class="d-flex justify-content-center">
        @if ($errors->any())
        <div class="col-md-12 text-center p-3">
          <div class="alert alert-danger" role="alert">
            @foreach ($errors->all() as $error)
                <p style="margin-bottom: 0rem;"><i class="fas fa-times"></i> {{ $error }}</p>
            @endforeach
          </div>
        </div>
        @endif

        @if (session('status'))
        <div class="col-md-12 text-center p-3">
          <div class="alert alert-success" role="alert">
              <i class="fas fa-check"></i> {{ session('status') }}
          </div>
        </div>
        @endif
      </div>


      <form method="POST" action="{{ route('contactPP') }}">
        @csrf
        <input name="idPromotion" type="hidden" value="{{ $promotion->id }}">
        <input name="emailPP" type="hidden" value="{{ $promotion->mailresponsable }}">
        <div class="form-row p-3">
            <div class="col-md-3">
                <label>Identité</label>
            </div>
            <div class="col-md-9">
                <input type="text" placeholder="Exemple : Marie Dupont" class="form-control" name="identite" value="{{ old('identite') }}" required>
            </div>
        </div>
        <div class="form-row p-2">
            <div class="col-md-3">
                <label>Adresse mail</label>
            </div>
            <div class="col-md-9">
                <input type="email" placeholder="Exemple : contact@1mix.com" class="form-control" name="email" value="{{ old('email') }}" required>
            </div>
        </div>
        <div class="form-row p-2">
            <div class="col-md-3">
                <label>Votre message</label>
            </div>
            <div class="col-md-9">
                <textarea class="form-control" maxlength="1500" name="message" rows="5" required>{{ old('message') }}</textarea>
            </div>
        </div>
        <div class="form-row p-2">
            <div class="col-md-3">
                <label>Captcha</label>
            </div>
            <div class="col-md-6">
              <input type="text" class="form-control" name="captcha" minlength="6" maxlength="6" required>
            </div>
            <div class="col-md-3 captcha">
                <img class="w-75 img-thumbnail" src="{!! Captcha::src() !!}"></img>
            </div>
        </div>
        <button class="btn btn-success" type="submit"><i class="fas fa-paper-plane"></i> Envoyer</a>
        </form>

  </section>
@stop

resources/views/editor.blade.php
<textarea class="form-control" id="summary-ckeditor" name="summary-ckeditor"></textarea>

<script src='{{asset("ckeditor/ckeditor.js")}}'></script>
<script>CKEDITOR.replace('summary-ckeditor');</script>

resources/views/fiche.blade.php
@extends('template')

@section('title', 'Remplir la fiche de stage')

@section('content')
<link rel="stylesheet" href="{{ asset('/css/landing-page.css') }}">

<style>
header.masthead {
    position: relative;
    background-color: #343a40;
    background: url({{ asset('storage/fiche.jpg') }}) no-repeat center center;
    background-size: cover;
    padding-top: 8rem;
    padding-bottom: 8rem;
}

input::-webkit-calendar-picker-indicator {
  position: absolute;
  width: 100%;
  height: 100%;
  opacity: 0;
}

@media (max-width: 768px) {
    .w-75 {
        width: 30%!important;
      }
    .captcha {
      padding-bottom: 1rem;
    }
}
</style>

<script>
$(document).ready(function() {
  $("#step2").hide();
  $("#buttonStep").click(function(){
    $("#step1").hide();
    $("#step2").show();
    $("#buttonBack").hide();
  });
});
</script>

<header class="masthead text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <h1 class="mb-5">Remplir la fiche de stage</h1>
      </div>
    </div>
  </div>
</header>

<section class="testimonials text-center bg-light pt-5">
    <div class="container">

      <div class="d-flex justify-content-center" id="buttonBack">
        <a class="btn btn-danger" href="{{ URL::previous() }}" role="button"><i class="fas fa-arrow-circle-left"></i> Retour</a>
      </div>

      <div class="d-flex justify-content-center">
        @if ($errors->any())
        <script>
        $(document).ready(function() {
            $("#step1").show();
            $("#step2").show();
            $("#buttonStep").hide();
          });
        </script>

        <div class="col-md-12 text-center p-3">
          <div class="alert alert-danger" role="alert">
            @foreach ($errors->all() as $error)
                <p style="margin-bottom: 0rem;"><i class="fas fa-times"></i> {{ $error }}</p>
            @endforeach
          </div>
        </div>
        @endif
        @if (session('status'))
        <div class="col-md-12 text-center p-3">
          <div class="alert alert-success" role="alert">
              <i class="fas fa-check"></i> {{ session('status') }}
          </div>
        </div>
        @endif
      </div>

      <form method="POST" action="{{ route('insertFiche') }}">
        @csrf
        <input name="stage_id" type="hidden" value="{{ $stage->id }}">
        <div class="row p-3" id="step1">
          <div class="col-md-4">
              <div class="form-group">
                <label>Nom de l'élève</label>
                <input name="nom" type="text" class="form-control" placeholder="Exemple : Vuillemin" value="{{ old('nom') }}" required>
              </div>
          </div>
          <div class="col-md-4">
              <div class="form-group">
                <label>Prénom de l'élève</label>
                <input name="prenom" type="text" class="form-control" placeholder="Exemple : Hugo" value="{{ old('prenom') }}" required>
              </div>
          </div>
          <div class="col-md-4">
              <div class="form-group">
                <label>Classe</label>
                <input name="classe" type="text" class="form-control" placeholder="Exemple : BTS SIO 2 TP" value="{{ $stage->promotion->nom }}" required readonly>
              </div>
          </div>
          <div class="col-md-12">
              <div class="form-group">
                <label>Lieu du stage</label>
                <input name="lieuDuStage" type="text" class="form-control" placeholder="Exemple : 3 rue Crissey 39100 DOLE" value="{{ old('lieuDuStage') }}" required>
              </div>
          </div>
          <div class="col-md-6">
            <label>Date de début du stage</label>
            <div class="input-group mb-3">
              <input type="date" name="dateDebut" max="3000-12-31"min="1000-01-01" class="form-control" value="{{ $stage->dateDebut }}" readonly>
              <div class="input-group-append">
                <span class="input-group-text" id="datepickericon"><i class="far fa-calendar-alt"></i></span>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <label>Date de fin du stage</label>
            <div class="input-group mb-3">
              <input type="date" name="dateFin" max="3000-12-31"min="1000-01-01" class="form-control" value="{{ $stage->dateFin }}" readonly>
              <div class="input-group-append">
                <span class="input-group-text" id="datepickericon"><i class="far fa-calendar-alt"></i></span>
              </div>
            </div>
          </div>
          <div class="col-md-12 pb-3">
            <label>Horaires prevus durant le stage</label>
            <textarea class="form-control" name="horaires" rows="6" placeholder="Exemple : &#10;Lundi - 08:00 à 16h30, &#10;Mardi - 08:00 à 16h30, &#10;Mercredi - 08:00 à 16h30, &#10;Jeudi - 08:00 à 16h30, &#10;Vendredi - 08:00 à 16h30" required>{{ old('horaires') }}</textarea>
          </div>
          <div class="col-md-12 pb-3">
            <label>Activité durant le stage</label>
            <textarea class="form-control" name="activiteDurantLeStage" rows="3" placeholder="Exemple : Réparation et maintenance du parc informatique de l'entreprise." required>{{ old('activiteDurantLeStage') }}</textarea>
          </div>
          <div class="col-md-12">
            <button id="buttonStep" type="button" class="btn btn-success">Etape suivante <i class="fas fa-arrow-circle-right"></i></button>
          </div>
          </div>
          <div class="row p-3" id="step2">
          <div class="col-md-12">
              <div class="form-group">
                <label>Adresse de l'entreprise</label>
                <input name="adresse" type="text" class="form-control" placeholder="Exemple : 3 rue Crissey 39100 DOLE" value="{{ old('adresse') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Raison sociale de l'entreprise</label>
                <input name="raisonSociale" type="text" class="form-control" placeholder="Exemple : SARL / SELAR / SELAS" value="{{ old('raisonSociale') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Téléphone de l'entreprise</label>
                <input name="telephone" type="text" class="form-control" placeholder="Exemple : 03 84 69 99 99" value="{{ old('telephone') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Fax de l'entreprise</label>
                <input name="fax" type="text" class="form-control" placeholder="Exemple : 03 84 69 99 98" value="{{ old('fax') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Nombre de salariés</label>
                <input name="nombreDeSalaries" type="text" class="form-control" placeholder="Exemple : 11" value="{{ old('nombreDeSalaries') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Email de l'entreprise</label>
                <input name="emailDeEntreprise" type="email" class="form-control" placeholder="Exemple : contact@1mix.com" value="{{ old('emailDeEntreprise') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Code APE</label>
                <input name="codeAPE" type="text" class="form-control" placeholder="Exemple : 0143Z" value="{{ old('codeAPE') }}" required>
              </div>
          </div>
          <div class="col-md-12">
              <div class="form-group">
                <label>Descriptif de l'activité</label>
                <input name="descriptifDeActivite" type="text" class="form-control" placeholder="Exemple : Blanchisserie-teinturerie de détail" value="{{ old('descriptifDeActivite') }}" required>
              </div>
          </div>
          <div class="col-md-12">
              <div class="form-group">
                <label>Adresse du siège social</label>
                <input name="adresseDuSiegeSocial" type="text" class="form-control" placeholder="Exemple : 3 rue Crissey 39100 DOLE" value="{{ old('adresseDuSiegeSocial') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Numéro de SIRET</label>
                <input name="siret" type="text" class="form-control" placeholder="Exemple : 362 521 879 00034" value="{{ old('siret') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Identité du dirigeant</label>
                <input name="identiteDuDirigeant" type="text" class="form-control" placeholder="Exemple : Patrick Montclar" value="{{ old('identiteDuDirigeant') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Identité du reponsable du personnel</label>
                <input name="identiteDuResponsableDePersonnel" type="text" class="form-control" placeholder="Exemple : Yannick Baccide" value="{{ old('identiteDuResponsableDePersonnel') }}" required>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                <label>Nom et fonction du reponsable de stage</label>
                <input name="nomEtFonctionDuResponsableDeStage" type="text" class="form-control" placeholder="Exemple : Thomas Dove - Ressource Humaine" value="{{ old('nomEtFonctionDuResponsableDeStage') }}" required>
              </div>
          </div>
          <div class="col-md-8">
              <div class="form-group">
                <label>Captcha</label>
                <input name="captcha" type="text" class="form-control" minlength="6" maxlength="6" required>
              </div>
          </div>
          <div class="col-md-4 captcha">
            <img class="img-thumbnail img-fluid w-75" src="{!! Captcha::src() !!}"></img>
          </div>
          <div class="col-md-12">
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Valider la fiche de stage</button>
          </div>
        </div>
      </form>
  </section>
@stop